services:
  # Uretim ortami icin PHP-FPM override
  app:
    build:
      target: production
    volumes:
      - storage_data:/var/www/html/storage/app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  # Nginx - sadece port 80 (Cloudflare SSL yonetir)
  nginx:
    ports:
      - "80:80"
